INSERT INTO PURCHASE (CUSTOMERNAME, PRODUCT, PURCHASEDATE) VALUES ('John', 'Basketball', DATE '2024-01-15');
INSERT INTO PURCHASE (CUSTOMERNAME, PRODUCT, PURCHASEDATE) VALUES ('Paul', 'Football', DATE '2024-02-20');
INSERT INTO PURCHASE (CUSTOMERNAME, PRODUCT, PURCHASEDATE) VALUES ('Mary', 'Tennis Racket', DATE '2024-03-10');
INSERT INTO PURCHASE (CUSTOMERNAME, PRODUCT, PURCHASEDATE) VALUES ('Susan', 'Soccer Ball', DATE '2024-04-05');