/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.example;

import java.util.Date;
import java.util.List;

import org.springframework.context.ApplicationContext;
import org.springframework.context.annotation.AnnotationConfigApplicationContext;

import com.example.entity.Purchase;
import com.example.service.PurchaseService;
import com.example.service.Register;

public class App {

    public static void main(String[] args) {
        System.out.println("spring-jdbc app is starting...");
        ApplicationContext spring = new AnnotationConfigApplicationContext(Config.class);
        
        // Demonstrate original features
        Register register = spring.getBean(com.example.service.Register.class);
        double total = register.computeTotal(100.00);
        System.out.println("Sales Tax Calculator Total: " + total);
        
        // Demonstrate JDBC features
        PurchaseService purchaseService = spring.getBean(PurchaseService.class);
        System.out.println("\n--- Purchase Database Demo ---");
        
        List<Purchase> purchases = purchaseService.findAllPurchases();
        System.out.println("All Purchases from Database:");
        for (Purchase purchase : purchases) {
            System.out.println("  " + purchase);
        }
        
        System.out.println("\nSpring JDBC Demo completed successfully!");
    }
}
